name: PR Check

on:
  pull_request:

jobs:
  check-index:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check index.html
        run: test -f index.html